# Generated by Django 5.0.4 on 2024-05-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('bio', models.TextField()),
                ('hobbies', models.CharField(choices=[('anime', 'Anime'), ('games', 'Games'), ('photography', 'Photography'), ('cooking', 'Cooking'), ('drawing', 'Drawing'), ('dance', 'Dance'), ('writing', 'Writing'), ('movies', 'Movies'), ('video', 'Video'), ('painting', 'Painting'), ('learning', 'Learning')], max_length=200)),
            ],
        ),
    ]
