# Generated by Django 5.0.4 on 2024-05-02 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibeus', '0002_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
    ]
